#!/usr/bin/env php

<?php

require_once __DIR__ . '/vendor/autoload.php';

use Infrastructure\Core\Kernel;

echo '
                                  
███╗   ██╗     █████╗     ███████╗
████╗  ██║    ██╔══██╗    ██╔════╝
██╔██╗ ██║    ███████║    █████╗  
██║╚██╗██║    ██╔══██║    ██╔══╝  
██║ ╚████║    ██║  ██║    ██║     
╚═╝  ╚═══╝    ╚═╝  ╚═╝    ╚═╝     
                                  
==================================
      Its Not A Framework
==================================
                                  
';

Kernel::bootCli();